name: Rails Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rails_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and start containers
        run: |
          docker compose build
          docker compose up -d db

      - name: Run tests
        run: |
          docker compose run --rm backend sh -c "
            bundle exec rails db:create db:schema:load RAILS_ENV=test &&
            bundle exec rails test
          "
        env:
          RAILS_ENV: test
          DATABASE_URL: postgresql://postgres:password@db:5432/rr_test

      - name: Cleanup
        if: always()
        run: docker compose down -v
